 CREATE TABLE "GEN_IXNDB"."CLOUD_STA_IXNS" 
   (	"STARTDATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"CONVERSATION_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"QUEUE" VARCHAR2(500 CHAR), 
	"LOB" VARCHAR2(20 BYTE), 
	"AGENT_ID" VARCHAR2(500 CHAR), 
	"CALLDURATION" NUMBER, 
	"SENTIMENTSCORE" NUMBER, 
	"CUSTOMERDURATIONPERCENTAGE" NUMBER, 
	"AGENTDURATIONPERCENTAGE" NUMBER, 
	"SILENCEDURATIONPERCENTAGE" NUMBER, 
	"IVRDURATIONPERCENTAGE" NUMBER, 
	"ACDDURATIONPERCENTAGE" NUMBER, 
	"OVERTALKDURATIONPERCENTAGE" NUMBER, 
	"OTHERDURATIONPERCENTAGE" NUMBER, 
	"OVERTALKCOUNT" NUMBER, 
	"SENTIMENTTREND" NUMBER, 
	"MARKET_TYPE" VARCHAR2(50 BYTE), 
	"CLIENTID" VARCHAR2(50 BYTE), 
	"ANI" VARCHAR2(500 CHAR), 
	"PARTY_ID" VARCHAR2(50 BYTE), 
	"AGENTDURATION" NUMBER, 
	"DNIS" VARCHAR2(500 CHAR), 
	"AUTHENTICATION_TYPE" VARCHAR2(500 CHAR), 
	"EMPATHYSCORE" NUMBER, 
	"WORK_TEAMS" VARCHAR2(500 CHAR), 
	"ACW_TIME" NUMBER, 
	"CALL_HANDLE_TIME" NUMBER, 
	"DIVISION" VARCHAR2(500 CHAR), 
	"INTERACTION_CATEGORIES" VARCHAR2(500 CHAR), 
	"BALANCE" NUMBER, 
	"PLAN_ID" NUMBER, 
	"SEP_FROM_SERVICE" VARCHAR2(50 BYTE), 
	"MP_STATUS" NUMBER, 
	 CONSTRAINT "CLOUD_STA_IXNS_PK" PRIMARY KEY ("CONVERSATION_ID")


/Think longer /powerpoint presentation /Deep analysis create a DOWNLOADABLE sprofessional and minimalistic powerpoint presentation for my Full stack application dashboard for Genesys cloud contact center data made using react node mysql...Name and itle of dashbaord is "Acoustic Analysis Dashboard"..it contains following features create 1-2 slides for each feature..I HAVE given you the screenshots..you may also on high level refer to docx word documentation file I provided but dont take everything from there..focus on details and content and make it rich and buisness presentable...after explainging features add a slide for positive business impact i.e. like powerful tool to explore and analyze data from acoustic metrics perspective and also be able to use filters inn genereal to get basic reporting when not using the metrics. Total end to end solution that provides both high level and low level view for analysis and inspires data driven buisness decisions..add one more empty slide at last with title as client feedback here's a summary of features 1.statistical cards implemented for different acoustic data metrics Gives total count for selected interval, % change compared to past interval of same size and day by day count 2.Global pre-filters filter data in all components of dashboard i.e. globally using different KVP's 3.grouped bar chart Group by agent name division queue etc and sort conversation data as per selected tab 4.stacked bar chart allows user to look into acoustic data % out of total call duration in a stacked view and also shows further detaisl for a conversation when user hovers over any bar 5.download preview for each chart data which allows user to view conversation details and be able to download as an excel file reference Slide Structure: Title Slide - Professional introduction with tech stack display Statistical Cards Overview - Real-time metrics explanation with visual examples Statistical Cards Technical - Advanced features and metric types Global Pre-Filters - Unified data control system Grouped Bar Chart Overview - Comparative analysis capabilities Grouped Bar Chart Technical - Advanced analytics and planned enhancements Stacked Bar Chart Overview - Conversation composition visualization Stacked Bar Chart Features - Granular intelligence features Download Preview & Export - Comprehensive data extraction capabilities Business Impact - Strategic advantages and value proposition ROI and Metrics - Measurable outcomes and efficiency gains Client Feedback - Empty slide for collecting client input remember give a ppt as a link that i can download
