WITH phrase_counts AS (
  SELECT
    CONVERSATION_ID,
    TOPICNAME,
    TOPICPHRASE,
    COUNT(*) AS PHRASE_COUNT
  FROM HIST_TOPICS_IXNS
  WHERE STARTDATE BETWEEN TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
                      AND TO_TIMESTAMP('2024-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
  GROUP BY CONVERSATION_ID, TOPICNAME, TOPICPHRASE
),

topic_arrays AS (
  SELECT
    CONVERSATION_ID,
    TOPICNAME,
    '[' || LISTAGG(
      '"' || PHRASE_COUNT || 'x ' || REPLACE(TOPICPHRASE, '"', '\"') || '"',
      ','
    ) WITHIN GROUP (ORDER BY TOPICPHRASE) || ']' AS topic_phrases
  FROM phrase_counts
  GROUP BY CONVERSATION_ID, TOPICNAME
),

topic_json AS (
  SELECT
    CONVERSATION_ID,
    '{' || LISTAGG(
      '"' || TOPICNAME || '":' || topic_phrases,
      ','
    ) WITHIN GROUP (ORDER BY TOPICNAME) || '}' AS TOPIC_PHRASES_JSON
  FROM topic_arrays
  GROUP BY CONVERSATION_ID
),

base_data AS (
  SELECT *
  FROM (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY CONVERSATION_ID ORDER BY STARTDATE) AS rn
    FROM HIST_TOPICS_IXNS
    WHERE STARTDATE BETWEEN TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
                        AND TO_TIMESTAMP('2024-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
  )
  WHERE rn = 1
)

-- Final output: merge compact topic JSON into your full record
SELECT
  b.CONVERSATION_ID,
  b.CALL_DURATION,
  b.AGENT_DURATION,
  b.SENTIMENT_SCORE,
  t.TOPIC_PHRASES_JSON
FROM base_data b
JOIN topic_json t
  ON b.CONVERSATION_ID = t.CONVERSATION_ID;
